version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: 'yarn install --pure-lockfile'
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: lint 
          command: './node_modules/.bin/eslint --debug . --format tap | ./node_modules/.bin/tap-xunit'
      - run:
          name: test 
          command: './node_modules/.bin/babel-node source/test | ./node_modules/.bin/tap-xunit'
          environment:
            NODE_PATH: source
      - run:
          name: build 
          command: 'yarn run build'
      - run:
          name: start 
          command: 'yarn run start'
      - run:
          name: test 
          command: 'yarn run test:e2e'
